export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";


export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";
export const HIDE_HEADER = "HIDE_HEADER";

export const UPDATE_ALERT_DATE = "UPDATE_ALERT_DATE";
export const UPDATE_ALERT_LIST = "UPDATE_ALERT_LIST";
export const CLEAR_ALERT_LIST = "CLEAR_ALERT_LIST";
export const REMOVE_ALERT_FROM_LIST = "REMOVE_ALERT_FROM_LIST";

export const SHOW_SPINNER = "SHOW_SPINNER";
export const HIDE_SPINNER = "HIDE_SPINNER";

export const CLEAR_HIGHLIGHT_WINNER = "CLEAR_HIGHLIGHT_WINNER";
export const UPDATE_HIGHLIGHT_WINNER = "UPDATE_HIGHLIGHT_WINNER";

export const CLEAR_HIGHLIGHT_PARTICIPANT = "CLEAR_HIGHLIGHT_PARTICIPANT";
export const UPDATE_HIGHLIGHT_PARTICIPANT = "UPDATE_HIGHLIGHT_PARTICIPANT";



