export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";


export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const CLEAR_USER_PROFILE = "CLEAR_USER_PROFILE";
export const HIDE_HEADER = "HIDE_HEADER";

export const UPDATE_ALERT_DATE = "UPDATE_ALERT_DATE";
export const UPDATE_ALERT_LIST = "UPDATE_ALERT_LIST";
export const CLEAR_ALERT_LIST = "CLEAR_ALERT_LIST";
export const REMOVE_ALERT_FROM_LIST = "REMOVE_ALERT_FROM_LIST";

